services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: next_app
    env_file:
      - .env.local
    environment:
      - NODE_ENV=production
      - CONVEX_DEPLOYMENT="${CONVEX_DEPLOYMENT:-default}"
    expose:
      - "3000"
    networks:
      - code-pair

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./public:/usr/share/nginx/html/public
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - code-pair

networks:
  code-pair:
    driver: bridge